---
- name: Install basic tools
  hosts: webserver
  vars_files:
    - vars.yml
  roles:
    - ssh

- name: Install Docker
  hosts: webserver
  become: true
  become_method: sudo
  vars_files:
    - vars.yml
  roles:
    - docker

#- name: Install applications
