---
- name: Install basic tools
  hosts: webserver
  vars_files:
    - vars.yml
  roles:
    - role: ssh
      tags: ssh_tag

- name: Install Docker
  hosts: webserver
  become: true
  become_method: sudo
  vars_files:
    - vars.yml
  roles:
    - role: docker
      tags: docker_tag

- name: Install BDD
  hosts: webserver
  become: true
  become_method: sudo
  vars_files:
    - vars.yml
  roles:
    - role: bdd
      tags: bdd_tag


#- name: Install applications
