---
- name: Install basic tools
  hosts: webserver
  vars_files:
    - vars.yml
  tags: ssh_tag
  roles:
    - role: ssh

- name: Install Jenkins
  hosts: webserver
  become: true
  become_method: sudo
  tags: jenkins_tag
  roles:
    - role: jenkins

- name: Install Docker
  hosts: webserver
  become: true
  become_method: sudo
  vars_files:
    - vars.yml
  tags: docker_tag
  roles:
    - role: docker

- name: Install BDD
  hosts: webserver
  become: true
  become_method: sudo
  vars_files:
    - vars.yml
  tags: bdd_tag
  roles:
    - role: bdd

#- name: Install applications
